### ISSUE TITLE
Vault enters an unmanagable loop when loading sub objects

### ISSUE THREAD

**Issue by davetao** [contentful/vault#103] opened 2015-09-22 14:40 UTC
Hi.

This is more of a problem with our content model itself but it would be a good idea to raise this as an issue and safeguard against it because it causes the app to freeze

At the moment, I have `Content Type A` that references `Content Type B`.
Due to poor design on our part, `Content Type B` contains links to `Content Type A` which causes the looping problem.

I do understand that the quickest way to solve this is to fix the links between the content types, but is there a strategy to introduce into the vault ORM that prevents such links from being loaded?

**Comment by tomxor** [comment] 2015-09-22 15:19
Do you mean that circular references cause infinite looping? if so, could you please tell me exactly which operation you're performing when this issue occurs?

**Comment by davetao** [comment] 2015-09-22 15:26
Yes. The Circular references is causing a loop.
I am loading up a single object and the ORM would automatically try and load linked objects as well.
Because there is a circular reference, it would loop infinitely

**Comment by tomxor** [comment] 2015-09-22 15:30
I'll try and reproduce this, if so this is certainly a bug.

**Comment by tomxor** [comment] 2015-09-22 16:18
@davetao I've just created a small test-case for circular references which works perfectly. Having two models referencing one another, I'm unable to reproduce this issue. Can you share more info for your use-case?

**Comment by tomxor** [comment] 2015-09-28 20:14
any update on this?

**Comment by davetao** [comment] 2015-09-28 22:13
It stemmed from a scenario where a simple call to an object was linked to many different objects in the scenario I described above. I basically solved the problem from my end by severing an unneccessary relationship so it didnt end up loading the whole database through one object.

**Comment by tomxor** [comment] 2015-09-29 19:36
Closing for now as I'm unable to reproduce Circular references are supported and there are test cases that verify they're working correctly. If this happens again please comment on this issue.

**Closed by tomxor** 2015-09-29 19:36 UTC

**Comment by kzotin** [comment] 2017-08-01 21:55
Seems we're having the same problem. It's quite urgent for us, and blocking delivery.

The model is fairly simple. We have Practices and Guides with 1--N relationship. 
Practice has `List<Guide> guides`, Guide has `Practice practice`.

Surprisingly, it works for some content items, and don't for others.
We're querying in following way:
```
.observe(Guide.class)
.where(Guide$Fields.REMOTE_ID + " = ?", guideId)
.all()
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
.subscribe(callback, throwable -> Logger.d("error:" + throwable));
```

Error stacktrace:
```
08-02 00:43:01.869 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.agilityscales.app.dev, PID: 5496
                                     java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                         at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                         at android.os.Handler.handleCallback(Handler.java:739)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:148)
                                         at android.app.ActivityThread.main(ActivityThread.java:5438)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                      Caused by: java.lang.StackOverflowError: stack size 1037KB
                                         at com.agilityscales.content.Practice.<init>(Practice.java:11)
                                         at com.agilityscales.content.Practice$$ModelHelper.fromCursor(Practice$$ModelHelper.java:46)
                                         at com.agilityscales.content.Practice$$ModelHelper.fromCursor(Practice$$ModelHelper.java:11)
                                         at com.contentful.vault.SqliteHelper.fromCursor(SqliteHelper.java:145)
                                         at com.contentful.vault.QueryResolver.all(QueryResolver.java:51)
                                         at com.contentful.vault.FetchQuery.resolveAll(FetchQuery.java:30)
                                         at com.contentful.vault.FetchQuery.resolveFirst(FetchQuery.java:37)
                                         at com.contentful.vault.LinkResolver.resourceForLink(LinkResolver.java:197)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:96)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                         at com.contentful.vault.LinkResolver.resolveLinksForField(LinkResolver.java:67)
                                         at com.contentful.vault.LinkResolver.resolveLinks(LinkResolver.java:55)
                                         at com.contentful.vault.LinkResolver.getCachedResourceOrFetch(LinkResolver.java:100)
                                     	at com.conten

```

**Comment by kzotin** [comment] 2017-08-01 22:09
Model & database dump can be found here:
https://drive.google.com/drive/u/0/folders/0BzDAFAs4761_bDYwVy04eF95V2s

Please let me know when you delete them, I'll stop sharing.
